# https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-and-collections-from-the-same-requirements-yml-file
# ansible-galaxy install -r roles/requirements.yml
---
roles:
  # https://github.com/lablabs/ansible-role-rke2
  - name: lablabs.rke2
    src: https://github.com/lablabs/ansible-role-rke2.git
    scm: git

collections: []
  # - name: awx.awx
  #   source: https://galaxy.ansible.com
