ansible_user: erhhung

# https://docs.ansible.com/projects/ansible/latest/playbook_guide/playbooks_privilege_escalation.html#become-connection-variables
ansible_become_password: "{{ sudo_pass['cosmos'] }}"
